version: '3'
networks:
  my-network:
    driver: bridge
services:
  web_api:
    image: ricardogaefke/ricardogaefke-webjobs:web_site_cloud
    container_name: web-api
    networks:
      - my-network
  nginx:
    image: ricardogaefke/ricardogaefke-webjobs:mynginx_cloud
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    networks:
      - my-network